#!/bin/bash
cd $(dirname $0)

# exit when any command fails
set -e

# Minecraft version
VER="1.13.2"
JAR_PATH="$(pwd)/../jar/minecraft_server.$VER.jar"
MCEXPLORE_PATH="$(pwd)/../mcexplore/mcexplore.py"
# Temporal folder
SERVER_DIR=$(mktemp -dp /dev/shm/server)
LEVEL_SEED="$1"
# Generate 100x100 area
CHUNK_XSIZE="100"
GENERATED_WORLDS_DIR="$(pwd)/worlds/$VER"

mkdir -p $GENERATED_WORLDS_DIR

rm -rf $SERVER_DIR
mkdir $SERVER_DIR
cd $SERVER_DIR

# Bash is hard
#https://stackoverflow.com/a/13864829
if [ -z $LEVEL_SEED ]; then 
	#echo "var is unset";
	# Use random seed
	# TODO: this will use the random seed generated by the minecraft server
	# (which uses 48 bits of entropy because of Java.Random)
	# If you want a true 64-bit integer, generate and set it here
	LEVEL_SEED=""
	# If you write 'level-seed=' into server.properties, the server will not
	# write the generated seed back...
	#echo "level-seed=$LEVEL_SEED" > server.properties

	# Use timestamp as seed
	#LEVEL_SEED=$(date +%s)
	#echo "level-seed=$LEVEL_SEED" > server.properties
	WORLD_ZIP="${GENERATED_WORLDS_DIR}/$(mktemp world.XXXXXXXXXX.zip)"
else
	echo "level-seed=$LEVEL_SEED" > server.properties
	WORLD_ZIP="${GENERATED_WORLDS_DIR}/world_${LEVEL_SEED}.zip"
fi

echo "eula=true" > eula.txt
# Start the server but stop it as soon as possible, when it finishes generating
# the spawn area
printf "stop\n" | java -Xmx1024M -Xms1024M -jar $JAR_PATH nogui
# Generate 100x100 chunk area
python3 $MCEXPLORE_PATH --command="java -Xmx1024M -Xms1024M -jar $JAR_PATH nogui" $CHUNK_XSIZE
cd -

# Compress the world into a zip file because slime_seed_finder works faster
# with zip files
cd $SERVER_DIR
zip -r $WORLD_ZIP .
cd -

# This line scares me
rm -rf $SERVER_DIR

# Verify against slime_seed_finder
RUST_BACKTRACE=1 RUST_LOG=debug slime_seed_finder test-generation --mc-version=$VER --input-zip $WORLD_ZIP
